# Generated by Django 5.1.1 on 2024-11-04 17:22

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("officers", "0002_alter_officer_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="officer",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="officer",
            name="is_active",
        ),
        migrations.AddField(
            model_name="officer",
            name="last_active",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="officer",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddIndex(
            model_name="officer",
            index=models.Index(fields=["status"], name="officers_of_status_c978da_idx"),
        ),
        migrations.AddIndex(
            model_name="officer",
            index=models.Index(
                fields=["created_at"], name="officers_of_created_4a921b_idx"
            ),
        ),
    ]
