# Generated by Django 5.0.1 on 2024-11-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="rank",
            field=models.CharField(
                blank=True,
                choices=[
                    ("commander", "Commander"),
                    ("lieutenant", "Lieutenant"),
                    ("captain", "Captain"),
                    ("major", "Major"),
                    ("colonel", "Colonel"),
                ],
                max_length=50,
            ),
        ),
    ]
