# Generated by Django 5.1.1 on 2024-11-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="military_number",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="user",
            name="national_id",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
