# Generated by Django 5.1.1 on 2024-11-06 14:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("officers", "0003_alter_officer_options_remove_officer_is_active_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cache_key", models.CharField(max_length=100, unique=True)),
                ("cache_data", models.JSONField()),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["cache_key"], name="dashboard_d_cache_k_80159c_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="dashboard_d_expires_d6f0f7_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DashboardMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_type", models.CharField(max_length=50)),
                ("metric_value", models.FloatField()),
                ("metric_label", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["metric_type", "timestamp"],
                        name="dashboard_d_metric__f6b0e6_idx",
                    ),
                    models.Index(
                        fields=["category", "timestamp"],
                        name="dashboard_d_categor_107137_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PerformanceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_officers", models.IntegerField(default=0)),
                ("available_officers", models.IntegerField(default=0)),
                ("on_mission_officers", models.IntegerField(default=0)),
                ("on_leave_officers", models.IntegerField(default=0)),
                ("total_tasks", models.IntegerField(default=0)),
                ("pending_tasks", models.IntegerField(default=0)),
                ("in_progress_tasks", models.IntegerField(default=0)),
                ("completed_tasks", models.IntegerField(default=0)),
                ("overdue_tasks", models.IntegerField(default=0)),
                ("completion_rate", models.FloatField(default=0.0)),
                ("avg_response_time", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["date"], name="dashboard_p_date_9299a9_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("task", "Task"),
                            ("order", "Order"),
                            ("officer", "Officer"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("status", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dashboard_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_officer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to="officers.officer",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["activity_type", "timestamp"],
                        name="dashboard_a_activit_855bb4_idx",
                    ),
                    models.Index(
                        fields=["actor", "timestamp"],
                        name="dashboard_a_actor_i_944c3d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notify_on_metric_change", models.BooleanField(default=True)),
                ("notify_on_task_update", models.BooleanField(default=True)),
                ("notify_on_officer_status", models.BooleanField(default=True)),
                ("email_notifications", models.BooleanField(default=True)),
                ("push_notifications", models.BooleanField(default=True)),
                ("notification_threshold", models.FloatField(default=10.0)),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user"], name="dashboard_n_user_id_dbf067_idx")
                ],
            },
        ),
    ]
